#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libsolidity-compiler
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet */

const
  _crash_js_module =
    require(
      "crash-js");
/* global
     _cat */
const
  _cat =
    _crash_js_module._cat;
/* global
     _file_exists */
const
  _file_exists =
    _crash_js_module._file_exists;
/* global
     _mkdir */
const
  _mkdir =
    _crash_js_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _crash_js_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _crash_js_module._msg_error;
/* global
     _path_join */
const
  _path_join =
    _crash_js_module._path_join;
/* global
     _stat */
const
  _stat =
    _crash_js_module._stat;
const
  _evm_chains_info_module =
    require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
const
  _evm_wallet_module =
    require(
      "evm-wallet.js");
/* global
     _address_get */
const
  _address_get =
    _evm_wallet_module._address_get;
/* global
     _balance_check */
const
  _balance_check =
    _evm_wallet_module._balance_check;
/* global
     _msg_error_balance_insufficient */
const
  _msg_error_balance_insufficient =
    _evm_wallet_module._msg_error_balance_insufficient;
/* global
     _balance_get */
const
  _balance_get =
    _evm_wallet_module._balance_get;
/* global
     _balance_send */
const
  _balance_send =
    _evm_wallet_module._balance_send;
/* global
     _block_number_get_get */
const
  _block_number_get =
    _evm_wallet_module._block_number_get;
/* global
     _ethers_to_wei */
const
  _ethers_to_wei =
    _evm_wallet_module._ethers_to_wei;
/* global
     _provider_get */
const
  _provider_get =
    _evm_wallet_module._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _evm_wallet_module._msg_info_provider_generated;
/* global
     _price_gas_get */
const
  _price_gas_get =
    _evm_wallet_module._price_gas_get;
/* global
     _price_gas_transaction_get */
const
  _price_gas_transaction_get =
    _evm_wallet_module._price_gas_transaction_get;
/* global
     _seed_new */
const
  _seed_new =
    _evm_wallet_module._seed_new;
/* global
     _wallet_get */
const
  _wallet_get =
    _evm_wallet_module._wallet_get;
/* global
     _wallet_new */
const
  _wallet_new =
    _evm_wallet_module._wallet_new;

const
  _solidity_compiler_module =
    require(
      "./lib/compiler");
/* global
     _solidity_compiler */
const
  _solidity_compiler =
    _solidity_compiler_module._solidity_compiler;

module.exports = {
  _solidity_compiler:
    _solidity_compiler
};
