#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libsolidity-compiler
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet */

const
  _crash_js_module =
    await import(
      "libcrash-js");
/* global
     _cat */
const
  _cat =
    _crash_js_module._cat;
/* global
     _file_exists */
const
  _file_exists =
    _crash_js_module._file_exists;
/* global
     _mkdir */
const
  _mkdir =
    _crash_js_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _crash_js_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _crash_js_module._msg_error;
/* global
     _path_join */
const
  _path_join =
    _crash_js_module._path_join;
/* global
     _stat */
const
  _stat =
    _crash_js_module._stat;

function
  _evm_make(
    _install_backend) {
  true;
}

export {
  _evm_make
};

// module.exports = {
//   _evm_make:
//     _evm_make
// };
